### ISSUE TITLE
Error: Invalid regular expression

### ISSUE THREAD

**Issue by RedHatter** [aMarCruz/jscc#12]
Single line directives capture the comment ending token as part of the expression.
```
/* #if process.env.TARGET === 'chrome' */
```
```
Error: Invalid regular expression: missing / in expression "process.env.TARGET === 'chrome' */"
```
For languages such as css that don't have single line comments this means that directions must be two lines.
```
/* #if process.env.TARGET === 'chrome'
*/
```

**Comment by BobVarioa** [comment]
This can be fixed by adding a jscc comment, like so:
```css
/*#set _COLOR = "red" //*/
.hi {
    /*#if _COLOR === "red" //*/
    color: red; 
    /*#endif //*/
}
```
